# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  # Moar memory!
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  # Manage /etc/hosts on host and VMs
  config.hostmanager.enabled = false
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true  
  config.hostmanager.include_offline = true
  config.hostmanager.ignore_private_ip = false  
  
  config.vm.provision "shell", inline: <<-SHELL
    wget https://apt.puppetlabs.com/puppet5-release-$(lsb_release -cs).deb
    dpkg -i puppet5-release-$(lsb_release -cs).deb
    apt-get -qq update
    apt-get install -y puppet-agent
  SHELL

  
  # Setup the machines
  workers = 3.times.map { |i| "worker#{i}" }  

  workers.each_index do |idx|
    ip = "10.0.5.#{idx+100}"

    config.vm.define workers[idx] do |c|
      c.vm.hostname=workers[idx]
      c.vm.network :private_network, ip: ip
      
      c.vm.provision :shell, inline: 'echo Started a hadoop-worker node...'
      c.vm.provision :hostmanager

      
      c.vm.provision :puppet do |p|
        p.environment_path="environments"
        p.environment = "test"
        p.manifests_path = "environments/test/manifests"        
        p.manifest_file = "base-hadoop.pp"
        p.options = "--debug --verbose"          
      end      
    end
  end

  config.vm.define "master" , primary: true do |c|
    c.vm.hostname="master"
    c.vm.network :private_network, ip: "10.0.5.2"
    c.vm.provision :shell, inline: 'echo Started hadoop-master...'
    c.vm.provision :hostmanager
    
    c.vm.network :forwarded_port, guest: 9870, host: 50070 # NameNode web interface
    c.vm.network :forwarded_port, guest: 8088, host: 8088   # YARN web interface
    
    c.vm.provision :puppet do |p|
      p.environment_path="environments"
      p.environment = "test"
      p.manifests_path = "environments/test/manifests"
      p.manifest_file = "base-hadoop.pp"
      p.options = "--debug --verbose"
    end

    c.vm.provision "shell", run: "always" do |p|
      p.privileged=false
      p.inline= <<-SHELL
          source /home/vagrant/hadoop-common.sh      
          id
          start-dfs.sh
          start-yarn.sh
      SHELL
      
    end
  end

end

